### ISSUE TITLE
Templated function not displaying templated variables correctly in watch window

### ISSUE THREAD

**Issue by luis-reyes-a** [EpicGames/raddebugger#35] opened 2024-01-15 03:27 UTC
Hey, first off congratz on release!

Anyways, I have this templated function that creates a "T obj", where 'T' is the template typename.
Inspecting "obj" in the watch window shows nothing. Doing "(T *)&obj" says T is an unknown identifier. I thought maybe template support isn't their yet but what's interesting is that explicitly casting "&obj" to the instantiated type only shows parts of the struct members ... not all. Here are pictures of watch window in raddbg and visual studio

![rad_watch_window](https://github.com/EpicGames/raddebugger/assets/29178817/a2c441cd-f534-4cb2-88a7-e820558e8745)

![msvc_watch_window](https://github.com/EpicGames/raddebugger/assets/29178817/ab676925-c914-4418-8b2e-3008e52bc0dc)

**Comment by ryanfleury** [comment] 2024-01-15 04:27
What version are you running? Can you see if the same issue persists on the newest commit in `master`? I've been shaking out some type info issues this weekend; the Microsoft linker tends to keep stale types around, which may explain the missing fields, *and* the seemingly-two copies of `Crazy_Struct`, *and* I recently fixed a bug with recently-added-or-changed types failing to evaluate members altogether.

If you pull and build to check this, please rebuild your own program too, to ensure raddbg regenerates the debug info.

**Comment by ryanfleury** [comment] 2024-01-15 17:53
Thanks for the heads up! Yeah, I have noticed that before, although strangely enough, not *only* in RADDBG. So I'm not sure if it has to do with my own bugs in `src/font_cache`, or if it's someone else's bug, or some combination of the two. For now I'll close this issue (since it was originally about something else), but I'll keep my eye out for more occurrences of that.

If you keep seeing that issue, or if you find a solid repro, then please open another issue along with e.g. a RenderDoc capture of the problem, along with your computer's specs (e.g. GPU, driver versions, and so on).

Thanks!

**Comment by MohitSethi99** [comment] 2024-01-15 23:13
I'm still facing this issue with eastl::shared_ptr<T> where `ref.ref_count_sp` is not shown correctly.
![image](https://github.com/EpicGames/raddebugger/assets/29519295/e3b7232f-65f2-4354-9eae-9d25d58256b0)

This is how `ref_count_sp` looks
![image](https://github.com/EpicGames/raddebugger/assets/29519295/cf5bc116-b74f-46b4-a644-eec1a525104e)

**Comment by MohitSethi99** [comment] 2024-01-16 00:18
Turned out eastl::atomic has a parent so I guess it can be related to #48 
Sorry for the false positive, will wait for that one to be fixed and then validate this again.

**Comment by MohitSethi99** [comment] 2024-01-16 20:22
Tried https://github.com/EpicGames/raddebugger/commit/e2e1382508385410dcb025d50dc644e0a2831a97 but this seems like a completely different issue than #48.

Check `CameraConstantBuffer`

![image](https://github.com/EpicGames/raddebugger/assets/29519295/7545e267-b085-4558-aa93-48a190a2136b)

![image](https://github.com/EpicGames/raddebugger/assets/29519295/7cbf38d9-8d60-42bb-979e-575ae4ff9296)

**Comment by ryanfleury** [comment] 2024-01-16 21:08
Whoa, yeah, that is weird & definitely a different issue - RADDBG is using totally the wrong type info (even though it is visualizing the correct type's name, `ArcEngine::ConstantBuffer`?). To help me narrow this down, can you determine if this same issue occurs after deleting the PDB/RADDBG files for this build, and re-running?

**Comment by MohitSethi99** [comment] 2024-01-16 21:36
No luck, tried with deleting both PDB and RADDBG files.
Also, I just noticed many of my pure virtual classes are behaving like that.
Will confirm in a while.

**Comment by ryanfleury** [comment] 2024-01-16 21:39
That sounds like exactly the kind of C++ thing that we haven't tested very much, so glad we're hitting this now - I'll work on getting this all straightened out.

**Comment by MohitSethi99** [comment] 2024-01-16 21:44
Here's the trivial example:
![image](https://github.com/EpicGames/raddebugger/assets/29519295/54c84426-b103-4564-a451-9a14251b5ac1)

**Comment by ryanfleury** [comment] 2024-01-16 22:08
Great! Reproduced. I don't have the crazy `eastl::` types but I can confirm that the pure-virtual type is redirecting to a totally different type, for some reason... debugging now!

**Comment by ryanfleury** [comment] 2024-01-17 01:35
@MohitSethi99 As of my newest commits, the debugger should no longer display *incorrect* type info for pointers to pure-virtual classes, but it will *not* resolve base class pointers to their appropriate derived class types (based on the vtable function pointer), in the same way that VS does. That feature is a bit more involved; I've made significant progress but not quite done yet. Just giving you an update.

**Comment by MohitSethi99** [comment] 2024-01-17 09:28
Thanks for quick fixes.
Can confirm pure virtuals are not showing wrong data.
However child is not showing the parent's variables (pure or not doesn't matter).

Pure virtual:
<img width="1082" alt="image" src="https://github.com/EpicGames/raddebugger/assets/29519295/8c472b77-fa01-48f9-a474-7965120beef5">

Non pure virtual
<img width="1069" alt="image" src="https://github.com/EpicGames/raddebugger/assets/29519295/44121db2-8077-40cc-98dd-d88e229d4a9e">

If I remove virtual methods then it's working as expected.

**Comment by ryanfleury** [comment] 2024-01-17 18:38
Okay, that issue should be fixed as of a0a6fc0988f97f3cac103a539c2ebc03b6374dd7. Still working on auto-casting to the derived type based on the vtable pointer, stand by...

Thanks for bearing with me!

**Comment by MohitSethi99** [comment] 2024-01-17 19:10
Working as expected now, no worries, please take your time :)
And thankyou for this awesome debugger!

**Comment by ryanfleury** [comment] 2024-01-17 19:52
Wrapping up now. Base class pointers to derived class instances should shortly be detected by the debugger, implicitly casting the pointer to the derived type automatically (this can be casted away to the base class type if needed).

https://github.com/EpicGames/raddebugger/assets/12454169/95fba9f7-000a-41c9-966b-eaf1bf562035

**Comment by ryanfleury** [comment] 2024-01-17 21:30
Alright, that is in as of d3931fd3e247efaa0e18885c4b0e1881481891b1. Closing this issue now.

**Closed by ryanfleury** 2024-01-17 21:30 UTC

**Comment by MohitSethi99** [comment] 2024-01-17 21:43
Thanks for all your hard work!
Everything seems to be working except the derived pointer conversion in non virtual inheritance case.
![image](https://github.com/EpicGames/raddebugger/assets/29519295/b43c68e4-6f68-4cde-adeb-0843fcb396f5)

**Comment by ryanfleury** [comment] 2024-01-17 21:56
Yeah @MohitSethi99, this case is - as far as I know - effectively not analyzable from a debugger, because there is no virtual table pointer implicitly inserted by the compiler in an instance of `Pure`. The only way to *use* the actual `Child` contents is to either explicitly cast it (which can be done in the watch window), or to have a virtual function (which then adds a virtual table pointer, which can be used to auto-cast to a derived pointer).

Visual Studio has the same behavior in this case:
![image](https://github.com/EpicGames/raddebugger/assets/12454169/b2076ba8-47e1-4e64-a07d-6df86e3d516d)

**Comment by MohitSethi99** [comment] 2024-01-17 22:02
Sorry about naively pointing to the issue without checking in VS and thanks for all the info :)

**Comment by ryanfleury** [comment] 2024-01-17 22:03
No worries, glad I could help!
