### ISSUE TITLE
View snaps to bottom of file when stepping into a function

### ISSUE THREAD

**Issue by luis-reyes-a** [EpicGames/raddebugger#36] opened 2024-01-15 03:48 UTC
Hello, in this clip I'm trying to step into a function. When I do, first it focuses on the disassembly instruction. I step over and it takes takes me to the start of the function. When I step over again, the view scrolls all the way to the bottom of the file. Stepping over again, fixes this and takes me back to where I was in the function.

(I don't think it matters but I'm calling the function through a macro (it doesn't do anything special but some token concatenation to call the function)

https://github.com/EpicGames/raddebugger/assets/29178817/9fc5033b-2411-475f-aa84-fdafcd60d0ed

**Comment by ryanfleury** [comment] 2024-01-15 03:58
Hmm. I think this is two bugs in one. The first, the step-into stopping at the jump table, has been fixed in 5fe3f56d3311e3d9763998ba006f01e431c9a56d. The second is probably a new edge case in line info, so I'll put on my list to check that one out.

**Comment by luis-reyes-a** [comment] 2024-01-29 16:26
Hey Ryan, not sure if it helps but the view snapping to the bottom of the file happens ***EVERY*** time I step into a function. Looking at videos of other people using the debugger, it seems to not be the case. I suspect maybe it has to do with the way I laid out my debugger windows or something? Here's another recording of this happening in latest build [28e258b]

(Uploaded to youtube because it's too long for github)
https://youtu.be/DG7Wgvef-hI

**Comment by ryanfleury** [comment] 2024-01-29 17:45
I don't think it should have anything to do with the panel layout you have. Can you provide more information about how you're building your EXE - what compiler, what version, what flags, what linker, etc.? And, if possible, can you send me a small test EXE/PDB which minimally reproduces the issue on your end?

**Comment by luis-reyes-a** [comment] 2024-01-30 01:49
To build raddebugger, I'm using msvc 19.29.30133 and all I do is go to the root folder and run build.bat. 

I suspect it may be because the program I'm trying to debug is using msbuild. I tried to recreate the problem just making a build.bat that calls cl but couldn't make it happen. Making a project in visual studio and calling msbuild did it for me. I think it also only happens when you jump to a function in a different file. Here is an example project. Just step into the function calls I have in main()


[example.zip](https://github.com/EpicGames/raddebugger/files/14091819/example.zip)

**Comment by ryanfleury** [comment] 2024-01-30 14:06
Looks like this is because of the `/JMC` (Just My Code) option, which is presumably turned on by default with the usual msbuild setup. Looking into how the debugger ought to handle this.

**Comment by ryanfleury** [comment] 2024-01-30 14:18
This should be resolved in f130f23b3f2e80b38431d72e3ea78e54b915aa07. Let me know if you run into additional issues with it.

**Closed by ryanfleury** 2024-01-30 14:18 UTC
Labels: bug
