### ISSUE TITLE
Fields members are not shown when inspecting a pointer to this user defined type.

### ISSUE THREAD

**Issue by mistymntncop** [EpicGames/raddebugger#114] opened 2024-01-25 04:10 UTC
Try this code. If you inspect the variable "foo" in the Watch View none of the field members are shown - you only see the pointer value. You can't expand the type. This is contrast with the result from RemedyBG which shows all the field members.

![Untitlezzzd](https://github.com/EpicGames/raddebugger/assets/105329747/a98946f7-46ea-47ca-93db-68c63deb611b)

```
#include <stdio.h>
#include <stdint.h>

typedef struct {
    uint32_t a;
    uint32_t b;
    uint32_t c;
    uint32_t d;
} Foo;

int main(void) {
    Foo foo_ = {1,2,3,4};
    Foo *foo = &foo_;
    
    return 0;
}
```

**Comment by ryanfleury** [comment] 2024-01-25 04:34
Can you provide more information on how you are building this - what compiler, what version, with what flags, etc.? I am not seeing the same result on my end (x64 MSVC 19.23.28105.4), so this is probably a difference in how the compiler is generating the type reference for `foo`, and our converter is not resolving something correctly.

![image](https://github.com/EpicGames/raddebugger/assets/12454169/1c86700b-a63c-4251-904c-620741720e20)

**Comment by mistymntncop** [comment] 2024-01-25 06:09
I am building using x64 MSVC compiler version "19.28.29337" and linker version "14.28.29337.0" (Visual Studio 2019).
Compiled with these flags: "cl -Zi -Od test.c"

**Comment by ryanfleury** [comment] 2024-01-25 15:22
Do you mind sending me the EXE/PDB? I can't seem to reproduce with a variety of compilers/versions. And once you've set those aside, can you see if you get different results after deleting the PDB & recompiling?

**Comment by mistymntncop** [comment] 2024-01-25 20:45
Sure thing, it's freshly built so there shouldn't be a problem with previous compilation results in the PDB.
[test.zip](https://github.com/EpicGames/raddebugger/files/14057616/test.zip)

**Comment by ryanfleury** [comment] 2024-01-25 21:25
@mistymntncop Looks like this was due to some new ways of encoding structs/classes in PDB, that we previously did not have paths for in the converter. As of 1319a23f982eea5c88895d4c44fbaf8dad97b6fd, this should be fixed. Mind pulling from `dev`, building, and giving it a try? (To ensure correct results you may have to either rebuilt `test.c` or delete your existing `.raddbg`)

**Comment by mistymntncop** [comment] 2024-01-25 21:29
It is indeed working now :). Great :) !

**Closed** 2024-01-25 21:31 UTC
Labels: bug
